version: '3.3'

services:
  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/"
    command: python3 manage.py run
    volumes:
      - ./data/logs:/usr/src/app/data/logs/
    restart: always
    ports:
      - 127.0.0.1:${WH_PORT}:${WH_PORT}
    env_file:
      - ".env"
    depends_on:
      - db
      - redis
    networks:
    - tg_bot

  db:
    container_name: "${DB_CONTAINER_NAME:-db-container}"
    image: postgres:14
    environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASS}
        - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
    ports:
      - 127.0.0.1:${DB_EXPOSE_PORT}:5432
    networks:
      - tg_bot
    volumes:
      - ./data/postgres:/var/lib/postgresql

  redis:
    container_name: "${REDIS_CONTAINER_NAME:-redis-container}"
    image: redis:alpine
    command: "redis-server --requirepass ${REDIS_PASS:-password123}"
    restart: unless-stopped
    ports:
      - 127.0.0.1:${REDIS_EXPOSE_PORT}:6379
    networks:
      - tg_bot
    volumes:
      - ./data/redis:/data



networks:
  tg_bot:
    driver: bridge
