"""Create chats table

Revision ID: 121611586677
Revises: 73ffa12c03c8
Create Date: 2022-11-30 22:54:14.982090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121611586677'
down_revision = '73ffa12c03c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('mention', sa.String(length=255), nullable=True),
                    sa.Column('is_private', sa.Boolean(), nullable=False),
                    sa.Column('link', sa.String(length=225), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='unique')
    # ### end Alembic commands ###
